# Generated by Django 5.2.7 on 2025-10-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(verbose_name='Score (0-1000)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Risque Faible'), ('MEDIUM', 'Risque Modéré'), ('HIGH', 'Risque Élevé'), ('VERY_HIGH', 'Risque Très Élevé')], max_length=20)),
                ('factors_positive', models.JSONField(default=list, verbose_name='Facteurs positifs')),
                ('factors_negative', models.JSONField(default=list, verbose_name='Facteurs négatifs')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('features_used', models.JSONField(default=dict, verbose_name='Features utilisées')),
                ('shap_values', models.JSONField(default=dict, verbose_name='Valeurs SHAP')),
                ('ai_recommendation', models.CharField(choices=[('AUTO_APPROVE', 'Approbation automatique'), ('MANUAL_REVIEW', 'Examen manuel requis'), ('AUTO_REJECT', 'Rejet automatique')], max_length=20)),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Niveau de confiance (%)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='demands.creditdemand')),
            ],
            options={
                'verbose_name': 'Score de Crédit',
                'verbose_name_plural': 'Scores de Crédit',
                'db_table': 'credit_scores',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('days_late', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON_TIME', 'À temps'), ('LATE', 'En retard'), ('DEFAULT', 'Défaut')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
