# Generated by Django 5.2.7 on 2025-10-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du dashboard')),
                ('layout', models.JSONField(help_text='Configuration du layout')),
                ('widgets', models.JSONField(help_text='Widgets affichés')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('PORTFOLIO', 'Rapport Portefeuille'), ('PERFORMANCE', 'Rapport Performance'), ('COMPLIANCE', 'Rapport Conformité'), ('RISK', 'Rapport Risque'), ('COBAC', 'Déclaration COBAC'), ('BEAC', 'Déclaration BEAC'), ('IFRS9', 'Rapport IFRS9')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', max_length=10)),
                ('period_start', models.DateField(verbose_name='Début période')),
                ('period_end', models.DateField(verbose_name='Fin période')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('data', models.JSONField(default=dict, verbose_name='Données du rapport')),
                ('summary', models.JSONField(default=dict, verbose_name='Résumé')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
