# Generated by Django 5.2.7 on 2025-10-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('credit_type', models.CharField(choices=[('CONSUMPTION', 'Crédit à la consommation'), ('REAL_ESTATE', 'Crédit immobilier'), ('AUTO', 'Crédit automobile'), ('BUSINESS', 'Crédit professionnel')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé (FCFA)')),
                ('duration_months', models.IntegerField(verbose_name='Durée (mois)')),
                ('purpose', models.TextField(verbose_name='Objet du crédit')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('IN_ANALYSIS', 'En analyse'), ('PENDING_ANALYST', 'En attente analyste'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_duration', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demands', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de Crédit',
                'verbose_name_plural': 'Demandes de Crédit',
                'db_table': 'credit_demands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Visible uniquement par les agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demands.creditdemand')),
            ],
            options={
                'db_table': 'demand_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PAYSLIP', 'Bulletin de salaire'), ('PROOF_OF_ADDRESS', 'Justificatif de domicile'), ('BANK_STATEMENT', 'Relevé bancaire'), ('OTHER', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Taille en octets')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demands.creditdemand')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
