# Generated by Django 5.2.7 on 2025-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdemand',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='creditdemand',
            name='status',
            field=models.CharField(choices=[('PENDING_ANALYST', 'En attente analyste'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING_ANALYST', max_length=20),
        ),
    ]
