# Generated by Django 5.2.7 on 2025-10-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('credit_type', models.CharField(choices=[('CONSUMPTION', 'Crédit à la consommation'), ('REAL_ESTATE', 'Crédit immobilier'), ('AUTO', 'Crédit automobile'), ('BUSINESS', 'Crédit professionnel')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant maximum')),
                ('min_duration_months', models.IntegerField(verbose_name='Durée minimum (mois)')),
                ('max_duration_months', models.IntegerField(verbose_name='Durée maximum (mois)')),
                ('base_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de base (%)')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux minimum (%)')),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux maximum (%)')),
                ('min_income_required', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Revenu minimum requis')),
                ('max_debt_ratio', models.DecimalField(decimal_places=2, default=33, max_digits=5, verbose_name='Taux endettement max (%)')),
                ('min_score_required', models.IntegerField(default=400, verbose_name='Score minimum requis')),
                ('required_documents', models.JSONField(default=list, help_text='Liste des documents obligatoires')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit de Crédit',
                'verbose_name_plural': 'Produits de Crédit',
                'db_table': 'credit_products',
            },
        ),
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la règle')),
                ('rule_type', models.CharField(choices=[('ELIGIBILITY', "Règle d'éligibilité"), ('SCORING_THRESHOLD', 'Seuil de scoring'), ('AMOUNT_LIMIT', 'Limite de montant'), ('DURATION_LIMIT', 'Limite de durée'), ('DEBT_RATIO', "Taux d'endettement"), ('AGE_LIMIT', "Limite d'âge"), ('INCOME_REQUIREMENT', 'Revenu minimum')], max_length=30)),
                ('credit_type', models.CharField(blank=True, help_text='Type de crédit (vide = toutes)', max_length=20)),
                ('condition', models.JSONField(help_text='Conditions sous forme JSON')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text="Ordre d'évaluation (plus élevé = prioritaire)")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règle Métier',
                'verbose_name_plural': 'Règles Métier',
                'db_table': 'business_rules',
                'ordering': ['-priority', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Règle respectée')),
                ('computed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField(help_text="Message d'explication")),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluations', to='demands.creditdemand')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.businessrule')),
            ],
            options={
                'verbose_name': 'Évaluation de Règle',
                'verbose_name_plural': 'Évaluations de Règles',
                'db_table': 'rule_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
